# 📊 Análise de Dados Musicais - Spotify & YouTube

## 🎯 Contexto do Projeto

**Você foi contratado pela Mateus Music** como Cientista de Dados para analisar o catálogo musical da empresa. Sua missão é explorar a base de dados contendo **mais de 20.000 músicas** e extrair insights valiosos sobre o desempenho dos artistas nas plataformas Spotify e YouTube.

A empresa precisa entender:
- Quem são os artistas mais relevantes
- Quais músicas performam melhor
- Como otimizar investimentos em marketing digital

## 📁 Sobre a Base de Dados

### Características Principais:
- **+20.000 músicas** no catálogo completo
- Dados de **Streams no Spotify** 
- Dados de **Views no YouTube**
- **Links dos vídeos** do YouTube para cada música
- **Metadados completos** de artistas e faixas

### 1. Importe o Pandas e mostre as informações gerais do dataframe

In [3]:
!pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\PROG02\AppData\Roaming\Python\Python313\site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\PROG02\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\PROG02\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\PROG02\AppData\Roaming\Python\Python313\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\PROG02\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd

df = pd.read_parquet("Dados_Artistas.parquet")

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20718 entries, 0 to 20717
Data columns (total 27 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Artist            20718 non-null  str
 1   Url_spotify       20718 non-null  str
 2   Track             20718 non-null  str
 3   Album             20718 non-null  str
 4   Album_type        20718 non-null  str
 5   Uri               20718 non-null  str
 6   Danceability      20716 non-null  float64
 7   Energy            20716 non-null  float64
 8   Key               20716 non-null  float64
 9   Loudness          20716 non-null  float64
 10  Speechiness       20716 non-null  float64
 11  Acousticness      20716 non-null  float64
 12  Instrumentalness  20716 non-null  float64
 13  Liveness          20716 non-null  float64
 14  Valence           20716 non-null  float64
 15  Tempo             20716 non-null  float64
 16  Duration_ms       20716 non-null  float64
 17  Url_youtube       20248 non-null  str
 18  Title             20248 non-null  str
 19  Channel           20248 non-null  str
 20  Views             20248 non-null  float64
 21  Likes             20177 non-null  float64
 22  Comments          20149 non-null  float64
 23  Description       19842 non-null  str
 24  Licensed          20248 non-null  object
 25  official_video    20248 non-null  object
 26  Stream            20142 non-null  float64
dtypes: float64(15), object(2), str(10)
memory usage: 31.0+ MB

### 2. Mostre as cinco primeiras linhas do dataframe

In [6]:
df.head(2)

,Artist,Url_spotify,Track,Album,Album_type,Uri,Danceability,Energy,Key,Loudness,...,Url_youtube,Title,Channel,Views,Likes,Comments,Description,Licensed,official_video,Stream
0,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Feel Good Inc.,Demon Days,album,spotify:track:0d28khcov6AiegSCpG5TuT,0.818,0.705,6.0,-6.679,...,https://www.youtube.com/watch?v=HyHNuVaZJ-k,Gorillaz - Feel Good Inc. (Official Video),Gorillaz,693555221.0,6220896.0,169907.0,Official HD Video for Gorillaz' fantastic trac...,True,True,1.040235e+09
1,Gorillaz,https://open.spotify.com/artist/3AA28KZvwAUcZu...,Rhinestone Eyes,Plastic Beach,album,spotify:track:1foMv2HQwfQ2vntFf9HFeG,0.676,0.703,8.0,-5.815,...,https://www.youtube.com/watch?v=yYDmaexVHic,Gorillaz - Rhinestone Eyes [Storyboard Film] (...,Gorillaz,72011645.0,1079128.0,31003.0,The official video for Gorillaz - Rhinestone E...,True,True,3.100837e+08

### 3. Vamos ver quais os artistas temos em nosso df e contar quantos artistas diferentes temos no nosso dataset

In [9]:
artistas_unicos = df.Artist.unique()
quantidades_artistas = artistas_unicos.size

### 4. Quais os 10 artistas com mais musicas em nosso dataset?

In [15]:
top_10_artistas = df["Artist"].value_counts().head(10)


print(top_10_artistas)

Artist
Gorillaz                 10
Red Hot Chili Peppers    10
50 Cent                  10
Metallica                10
Coldplay                 10
Daft Punk                10
Linkin Park              10
Radiohead                10
AC/DC                    10
Black Eyed Peas          10
Name: count, dtype: int64

### 5. Quais as 5 músicas com musicas com mais views no youtube?

In [16]:
df.sort_values("Views", ascending=False).head(5)

,Artist,Url_spotify,Track,Album,Album_type,Uri,Danceability,Energy,Key,Loudness,...,Url_youtube,Title,Channel,Views,Likes,Comments,Description,Licensed,official_video,Stream
1147,Luis Fonsi,https://open.spotify.com/artist/4V8Sr092TqfHkf...,Despacito,VIDA,album,spotify:track:6habFhsOp2NvshLv26DqMb,0.655,0.797,2.0,-4.787,...,https://www.youtube.com/watch?v=kJQP7kiw5Fk,Luis Fonsi - Despacito ft. Daddy Yankee,LuisFonsiVEVO,8.079649e+09,50788652.0,4252791.0,“Despacito” disponible ya en todas las platafo...,True,True,1.506598e+09
365,Daddy Yankee,https://open.spotify.com/artist/4VMYDCV2IEDYJA...,Despacito,VIDA,album,spotify:track:6habFhsOp2NvshLv26DqMb,0.655,0.797,2.0,-4.787,...,https://www.youtube.com/watch?v=kJQP7kiw5Fk,Luis Fonsi - Despacito ft. Daddy Yankee,LuisFonsiVEVO,8.079647e+09,50788626.0,4252791.0,“Despacito” disponible ya en todas las platafo...,True,True,1.506598e+09
12452,Ed Sheeran,https://open.spotify.com/artist/6eUKZXaKkcviH0...,Shape of You,÷ (Deluxe),album,spotify:track:7qiZfU4dY1lWllzX7mPBI3,0.825,0.652,1.0,-3.183,...,https://www.youtube.com/watch?v=JGwWNGJdvx8,Ed Sheeran - Shape of You (Official Music Video),Ed Sheeran,5.908398e+09,31047780.0,1130327.0,The official music video for Ed Sheeran - Shap...,True,True,3.362005e+09
14580,Charlie Puth,https://open.spotify.com/artist/6VuMaDnrHyPL1p...,See You Again (feat. Charlie Puth),See You Again (feat. Charlie Puth),single,spotify:track:2JzZzZUQj3Qff7wapcbKjc,0.689,0.481,10.0,-7.503,...,https://www.youtube.com/watch?v=RgKAFK5djSk,Wiz Khalifa - See You Again ft. Charlie Puth [...,Wiz Khalifa Music,5.773798e+09,40147674.0,2127346.0,Download the new Furious 7 Soundtrack Deluxe V...,True,True,1.521255e+09
12469,Wiz Khalifa,https://open.spotify.com/artist/137W8MRPWKqSmr...,See You Again (feat. Charlie Puth),See You Again (feat. Charlie Puth),single,spotify:track:2JzZzZUQj3Qff7wapcbKjc,0.689,0.481,10.0,-7.503,...,https://www.youtube.com/watch?v=RgKAFK5djSk,Wiz Khalifa - See You Again ft. Charlie Puth [...,Wiz Khalifa Music,5.773797e+09,40147618.0,2127345.0,Download the new Furious 7 Soundtrack Deluxe V...,True,True,1.521255e+09

### 6. Quais os 5 artistas com mais streams no spotify?

In [19]:
stream_por_artista = df.groupby("Artist")["Stream"].sum()
stream_por_artista.sort_values(ascending=False).head(5)

Artist
Post Malone     1.525126e+10
Ed Sheeran      1.439488e+10
Dua Lipa        1.340808e+10
XXXTENTACION    1.322435e+10
The Weeknd      1.303197e+10
Name: Stream, dtype: float64

### 7. Vamos converter e salvar o arquivo com parquet, para subir no github

In [22]:
### vamos converter o arquivo para parquet
df.to_parquet('Dados_Artistas.parquet', index=False)
df.to_csv("Dados_Artistas.csv", index=False)